#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo "
frontend olamidelateef
        bind *:80
        default_backend olamidelateef

backend olamidelateef
        balance roundrobin
        server 215514-web-01 34.229.161.138:80 check
        server 215514-web-02 3.84.161.114:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/EENABLED=0/ENABLED=1/g' /etc/default/haproxy
# Restart HAproxy service
sudo service haproxy restart
