#!/bin/bash

#Checks if the number of arguments is not equal to 1
#Output usage
#Exit with 1
#if [ $# -ne 1 ]; then
 #echo "Usage: $0 <username>"
 #exit 1
#fi

#Stores the provided username in a variable
#username="$1"

#Runs the whoami command under the provided username
sudo -u "$1" whoami 
