#!/bin/env bash

#Checks if the number of arguments is not equal to 1
#Echoes usage
#Exit with 1
if [$# -ne 1];then
echo "Usage: $0 <username>"
exit 1

#Stores the provided username in a variable
username = "$1"

#Runs the whoami command under the provided username
sudo -u "username" whoami 
